
        
        
on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@V3
    
    - name: Setup Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: 'Run npm'
      shell: bash
      run: |
        pushd .
        npm install
        npm start
        popd
        
    - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v1
        with: 
          app-name: node-rn
          publish-profile: ${{ secrets.AZURE_CREDITIALS }}
